### ISSUE TITLE
Does not work with 1.7.3

### ISSUE THREAD

**Issue by skiplyfrance** [rinogo/yourls-keep-query-string#1]
I installed the plugin, activated it, and nothing happens. 
Version 1.7.3.

**Comment by rinogo** [comment]
Perhaps you can share more information? I use it on 1.7.3 in production without issue.

**Comment by skiplyfrance** [comment]
As I don't have any error message, it is difficult to give more info. I will investigate, but maybe this could be a conflict with one of the activated plugins. I will let you know as soon as I can.

**Comment by rinogo** [comment]
Totally understandable. One thing you might try is to share an actual URL along with the expected and actual behavior.
