### ISSUE TITLE
redirect path, not only query string

### ISSUE THREAD

**Issue by nosovk** [rinogo/yourls-keep-query-string#2]
Is there a way to configure plugin to redirect not only query string, but also path connected to short url?

Like:
shortlink: httpx://yourls.com/shortlink
destination link: httpx://short.url/somepath
httpx://yourls.com/shortlink/someparam0/someparamX?param1=xxx&param2=yyy => httpx://short.url/somepath/someparam0/someparamX?param1=xxx&param2=yyy

**Comment by rinogo** [comment]
Hi, nosovk! This plugin only provides functionality for "keeping" the query string. However, the source for this plugin is straightforward and brief. You could certainly add the functionality yourself! You'll want to take a look at [line 14 of plugin.php](https://github.com/rinogo/yourls-keep-query-string/blob/master/plugin.php#L14).
